# create one bash_profile file
# cd ~/
# touch .bash_profile
# vi ~/.bash_profile
# Paste below env variables
# you need to run one more command in termninal after paste this : see below

export NODE_ENV=development
export RATE_LIMITER_BRAND_WINDOW_MIN=15
export RATE_LIMITER_BRAND_MAX_LIMIT=90
export RATE_LIMITER_FEED_WINDOW_MIN=15
export RATE_LIMITER_FEED_MAX_LIMIT=90
export RATE_LIMITER_PRODUCT_ROUTE_WINDOW_MIN=15
export RATE_LIMITER_PRODUCT_ROUTE_MAX_LIMIT=90
export RATE_LIMITER_ROUTE_PRODUCT_WINDOW_MIN=15
export RATE_LIMITER_ROUTE_PRODUCT_MAX_LIMIT=90
export RATE_LIMITER_CAMPAIGN_WINDOW_MIN=15
export RATE_LIMITER_CAMPAIGN_MAX_LIMIT=90
export RATE_LIMITER_CART_WINDOW_MIN=15
export RATE_LIMITER_CART_MAX_LIMIT=90
export RATE_LIMITER_CATEGORY_WINDOW_MIN=15
export RATE_LIMITER_CATEGORY_MAX_LIMIT=90
export RATE_LIMITER_MODERATION_WINDOW_MIN=15
export RATE_LIMITER_MODERATION_MAX_LIMIT=90
export RATE_LIMITER_SOCIAL_MEDIA_WINDOW_MIN=15
export RATE_LIMITER_SOCIAL_MEDIA_MAX_LIMIT=90
export RATE_LIMITER_TASK_WINDOW_MIN=15
export RATE_LIMITER_TASK_MAX_LIMIT=90
export RATE_LIMITER_SEARCH_WINDOW_MIN=15
export RATE_LIMITER_SEARCH_MAX_LIMIT=90
export RATE_LIMITER_STREAMING_WINDOW_MIN=15
export RATE_LIMITER_STREAMING_MAX_LIMIT=90

# source ~/.bash_profile

